### ISSUE TITLE
The requirements.txt is missing

### ISSUE THREAD

**Issue by anis-marrouchi** [peterw/StoryStorm#1]
Hi Peterw,

First off, I'd like to extend my heartfelt appreciation for all the valuable resources you've shared with us. Kudos to you for the brilliant work!

I was hoping to dive deeper into the project, but I noticed that the requirements.txt file seems to be absent. I was wondering if you might have any specific versions of libraries or packages that you're using in the project? If so, it would be incredibly helpful if you could share that information. From reading the code I have these dependencies:
```
replicate
langchain
elevenlabs
python-dotenv
streamlit
openai
```

Thank you once again for your dedication and efforts. Looking forward to hearing from you soon!

Best,
Anis Marrouchi

**Comment by anis-marrouchi** [comment]
I've forked the repo and added the missing requirements.txt. Do you want me the create a pull request @peterw ?

**Comment by peterw** [comment]
That would be useful, thanks!
